### ISSUE TITLE
zmapio fails to read zmap grid generated by ROXAR RMS

### ISSUE THREAD

**Issue by BeardedBeaver** [abduhbm/zmapio#1]
It's a very simple issue, RMS adds the following string
```
+Grid data starts after this line
```

after the end of header section (so basically after closing `@`). Zmapio tries to interpret this line as a z value and fails. You need to skip this line if occurs.

**Comment by BeardedBeaver** [comment]
Here's an example of such file
[test_rms_rect.txt](https://github.com/abduhbm/zmapio/files/4261064/test_rms_rect.txt)

**Comment by abduhbm** [comment]
Fixed, thank you for the report!
