### ISSUE TITLE
Z values are swapped in written grid

### ISSUE THREAD

**Issue by BeardedBeaver** [abduhbm/zmapio#2]
Here's the minimal reproducable example

```python

from zmapio import ZMAPGrid

zmap = ZMAPGrid('D:/tmp/test_pet_sq.txt')

out = ZMAPGrid(z_values = zmap.z_values, 
                min_x = zmap.min_x,
                max_x = zmap.max_x,
                min_y = zmap.min_y,
                max_y = zmap.max_y
                )

out.comments = ['test', 'zmapio']
out.nodes_per_line = 3
out.field_width = 15
out.decimal_places = 4
out.name = 'zmapio_test'

out.write('D:/tmp/test_zmapio_sq.txt')

```

Files for testing and output generated by this code are attached. As you can see the actual data in an output file differs from an input file. 

If I change `out` generation by the following:
```python
out = ZMAPGrid(z_values = zmap.z_values.swapaxes(0, 1), 
```

generated file looks correct. 

I'm not sure if it's input or output related issue but it doesn't look like a correct behaviour.

[test_pet_sq.txt](https://github.com/abduhbm/zmapio/files/4261036/test_pet_sq.txt)
[test_zmapio_sq.txt](https://github.com/abduhbm/zmapio/files/4261038/test_zmapio_sq.txt)

**Comment by abduhbm** [comment]
Fixed, thank you for the report!
